sudo: false
language: node_js
node_js:
  - v9
  - v8
  - v6
script:
  - npm run nsp
  - npm test
after_success: codecov
notifications:
  email: false
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
